spring:
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: none
      show-sql: true
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: postgres
    initialization-mode: always
    initialize: true
#    schema: classpath:/schema.sql
    continue-on-error: true
  liquibase:
    enabled: true
    change-log: classpath:db/changelog/liquibase-changeLog.xml
